# vi: ft=ruby

cask_args appdir: '~/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'neovim/neovim'
tap 'universal-ctags/universal-ctags'

cask 'xquartz'

brew 'asciinema'
brew 'diff-so-fancy'
brew 'direnv'
brew 'git'
brew 'jpeg'
brew 'elixir'
brew 'ffmpeg'
brew 'fish'
brew 'ghc'
brew 'git-lfs'
brew 'graphviz'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'jpegoptim'
brew 'jq'
brew 'lnav'
brew 'mobile-shell'
brew 'ncdu'
brew 'node'
brew 'optipng'
brew 'pandoc'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'shellcheck'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'wrk'
brew 'youtube-dl'
brew 'neovim/neovim/neovim'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD']

cask 'appcleaner'
cask 'battle-net'
cask 'caffeine'
cask 'dash'
cask 'flux'
cask 'gog-galaxy'
cask 'google-chrome'
cask 'gpgtools'
cask 'iterm2'
cask 'postgres'
cask 'qnapi'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'vlc'
cask 'zoomus'
