#!/bin/bash

if ! git config --get user.email >/dev/null
then
    printf "No identity set, set one using 'git identity <name>'" \
        | cowsay -f dragon-and-cow -W 60
    echo ""

    git identity --list

    exit 1
fi
