dir-colors:
	$(LN) dir_colors ${HOME}/.dir_colors

ctags:
	$(LN) ctags ${HOME}/.ctags

install: dir-colors ctags

clear:
	rm ${HOME}/.dir_colors ${HOME}/.ctags

.PHONY: install clear ctags dir-colors
